services:
  api:
    build: ./backend        
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: > 
      bash -c "pip3 install -r requirements.txt"
      bash -c "python manage.py makemigrations"
      bash -c "python manage.py migrate"
      bash -c "python manage.py runserver 0.0.0.0:8000"

  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    command: >
      bash -c "npm install"
      bash -c "npm start"